// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(grunt) {
    grunt.initConfig({
      lint: {
        all: ['grunt.js', 'lib/**/*.js', 'test/**/*.js']
      },
      jshint: {
        option: {
          browser: true
        }
      }
    });
    return grunt.registerTask('default', ['lint']);
  };

}).call(this);
