// Generated by CoffeeScript 1.3.3
(function() {

  app.get('/api/patterns/count', function(req, res) {
    console.log(GLOBAL.db);
    return db.collection('design_patterns', function(err, collection) {
      return collection.find().toArray(function(err, items) {
        return res.send(items);
      });
    });
  });

}).call(this);
