// Generated by CoffeeScript 1.3.3
(function() {
  var addPattern;

  addPattern = function(pattern, cb) {
    return db.collection('design_patterns', function(err, collection) {
      return collection.count(function(err, count) {
        pattern.id = count + 1;
        return collection.insert(pattern, function(err, doc) {
          return cb();
        });
      });
    });
  };

  app.get('/api/patterns', function(req, res) {
    return db.collection('design_patterns', function(err, collection) {
      return collection.find().toArray(function(err, items) {
        return res.send(items);
      });
    });
  });

  app.get('/api/patterns/count', function(req, res) {
    return db.collection('design_patterns', function(err, collection) {
      return collection.count(function(err, count) {
        return res.send(count.toString());
      });
    });
  });

  app.get('/api/patterns/:id', function(req, res) {
    var intId;
    intId = parseInt(req.params.id);
    return db.collection('design_patterns', function(err, collection) {
      return collection.findOne({
        id: intId
      }, function(err, item) {
        if (err != null) {
          return res.send(500);
        } else {
          if (item != null) {
            return res.send(item);
          } else {
            return res.send(404);
          }
        }
      });
    });
  });

  app.post('/api/patterns', function(req, res) {
    var new_pattern;
    new_pattern = {
      id: null,
      name: req.body.name,
      category: req.body.category,
      intent: req.body.intent,
      motivation: req.body.motivation,
      applicability: req.body.applicability,
      structure: req.body.structure
    };
    return addPattern(new_pattern, function() {
      return res.send(new_pattern);
    });
  });

  app.put('/api/patterns/:id', function(req, res) {
    var intId, updated_pattern;
    intId = parseInt(req.params.id);
    updated_pattern = {
      name: req.body.name,
      category: req.body.category,
      intent: req.body.intent,
      motivation: req.body.motivation,
      applicability: req.body.applicability,
      structure: req.body.structure
    };
    return db.collection('design_patterns', function(err, collection) {
      return collection.update({
        id: intId
      }, {
        $set: {
          name: updated_pattern.name,
          category: updated_pattern.category,
          intent: updated_pattern.intent,
          motivation: updated_pattern.motivation,
          applicability: updated_pattern.applicability,
          structure: updated_pattern.structure
        }
      }, function(err) {
        if (err != null) {
          return res.send(404);
        } else {
          return res.send(updated_pattern);
        }
      });
    });
  });

  app.del('/api/patterns/:id', function(req, res) {
    var intId;
    intId = parseInt(req.params.id);
    return db.collection('design_patterns', function(err, collection) {
      return collection.remove({
        id: intId
      }, function(err, removed) {
        if (err != null) {
          return res.send(500);
        } else {
          return res.send(removed);
        }
      });
    });
  });

}).call(this);
