// Generated by CoffeeScript 1.3.3
(function() {
  var MongoDBConnector, modules_url, mongodb, should;

  modules_url = '../node_modules';

  MongoDBConnector = require("./dao.js");

  mongodb = require('mongodb');

  should = require("" + modules_url + "/should");

  describe('Tests for MongoDBConnector', function() {
    var daoObj;
    daoObj = null;
    beforeEach(function() {
      return daoObj = new MongoDBConnector('design_patterns', 'alex.mongohq.com', 10001);
    });
    it('Can be instatiated with paraneters', function(done) {
      daoObj.should.have.property('dbName', 'design_patterns');
      daoObj.should.have.property('host', 'alex.mongohq.com');
      daoObj.should.have.property('port', 10001);
      daoObj.should.have.property('db');
      should.exist(daoObj.db);
      daoObj.db.should.be.an["instanceof"](mongodb.Db);
      return done();
    });
    return it('findAll returns a collection', function(done) {
      return daoObj.findAll(function(err, items) {
        items.should.be.json;
        items.should.be.an.instanceOf(Array);
        items.should.have.length(2);
        return done();
      });
    });
  });

}).call(this);
