// Generated by CoffeeScript 1.3.3
(function() {
  var MongoDBConnector, modules_url, mongodb, should;

  modules_url = '../node_modules';

  MongoDBConnector = require("./dao.js");

  mongodb = require('mongodb');

  should = require("" + modules_url + "/should");

  describe('Tests for MongoDBConnector', function() {
    var daoObj, new_pattern;
    daoObj = null;
    new_pattern = {
      "id": 3,
      "name": "Factory Method",
      "category": "Creational",
      "intent": "Define an interface for creating an object, but let subclasses decide which class to instantiate. Lets a class defer instantiation to subclasses",
      "motivation": "",
      "applicability": "",
      "structure": ""
    };
    beforeEach(function() {
      return daoObj = new MongoDBConnector('design_patterns', 'alex.mongohq.com', 10001);
    });
    it('Can be instatiated with paraneters', function(done) {
      daoObj.should.have.property('dbName', 'design_patterns');
      daoObj.should.have.property('host', 'alex.mongohq.com');
      daoObj.should.have.property('port', 10001);
      daoObj.should.have.property('db');
      should.exist(daoObj.db);
      daoObj.db.should.be.an["instanceof"](mongodb.Db);
      return done();
    });
    it('findAll returns my collection', function(done) {
      return daoObj.findAll(function(err, items) {
        items.should.be.an.instanceOf(Array);
        items.should.have.length(2);
        return done();
      });
    });
    it("count returns my collection's number", function(done) {
      return daoObj.count(function(err, count) {
        should.strictEqual(count, 2);
        return done();
      });
    });
    it("findById with id = 2 returns the Prototype pattern", function(done) {
      return daoObj.findById(2, function(err, item) {
        item.should.have.property('name', 'Prototype');
        return done();
      });
    });
    it("insert new_pattern (Factory Method) returns the pattern", function(done) {
      return daoObj.insert(new_pattern, function(err, docs) {
        docs[0].should.have.property('name', new_pattern.name);
        return done();
      });
    });
    it("update new_pattern returns the pattern updated", function(done) {
      var new_name;
      new_name = "Modified Name";
      new_pattern.name = new_name;
      return daoObj.update(new_pattern, function(err) {
        return daoObj.findById(new_pattern.id, function(err, item) {
          item.should.have.property('name', new_name);
          return done();
        });
      });
    });
    return it("delete new_pattern returns the removed alement", function(done) {
      return daoObj["delete"](new_pattern.id, function(err) {
        return daoObj.count(function(err, count) {
          should.strictEqual(count, 2);
          return done();
        });
      });
    });
  });

}).call(this);
